### ISSUE TITLE
Error in Testing

### ISSUE THREAD

**Issue by ishan11** [jbnunn/Alexa-MyQGarage#12]
hi

Whenever I try to test the skill i get the error "The remote endpoint could not be called, or the response it returned was invalid.".

Any help would be greatly appreciated

**Comment by CelticWebSolutions** [comment]
I have exactly the same issue.

I believe I've setup correctly although the amzn1.echo-sdk-ams.app.<your-alexa-skills-id> part that needs replacing, all I could find to us there was amzn1.ask.skill.d728a4f3-953e-4d62-8ad2-6797e589448a (changed some letter in that in case it was useable by somebody else)

I'm also not sure if it makes a difference but I'm in the UK, I think there may be a UK connection by the looks of the plugins available for many other plugins. 

Am I doings something wrong?

**Comment by ishan11** [comment]
I was able to figure out why it wasn't working for us. You need to do a couple steps differently when setting up in AWS. Follow the read me in #7 and it should work properly for you.

**Comment by CelticWebSolutions** [comment]
Hi Ishan11,

Thanks for your reply,  I've added my username and password in to main.py and I changed the amzn1.echo-sdk-ams.app.<your-alexa-skills-id> to be amzn1.ask.skill.d728a4f3-953e-4d62-8ad2-6797e589448a which looks different due to mine saying ask.skill ?

I then zipped the files up on my Mac using the command zip -r lambda-upload.zip main.py requests requests-2.9.1.dist-info

I changed the handler name to main.lambda_handler and gave it a whirl..

I just get The remote endpoint could not be called, or the response it returned was invalid :( any further tips?

**Comment by ishan11** [comment]
A couple of things that I could suggest are:
1. Are your username and passwords inside of "". In Python that is how you signify a string.
2. Maybe try deleting the AWS service and try starting again with the updated steps.

**Comment by CelticWebSolutions** [comment]
That was it!  I'd missed adding "" around the login detail, I did literally as it said and replaced <text> with my details.

Thank you so much for your help :)
