### ISSUE TITLE
Lambda now fails

### ISSUE THREAD

**Issue by CelticWebSolutions** [jbnunn/Alexa-MyQGarage#21]
I updated to your latest code but I still get the "There was a problem with the requested skills response" from Alexa.

Looking at Lambda logs I get the following

No JSON object could be decoded: ValueError
Traceback (most recent call last):
File "/var/task/main.py", line 32, in lambda_handler
login()
File "/var/task/main.py", line 95, in login
response = requests.get(login_uri()).json()
File "/var/task/requests/models.py", line 808, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
return _default_decoder.decode(s)
File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Any suggestions whats gone wrong please?

**Comment by bhusang** [comment]
I, too, have the same problem which cropped up today. I suspect that the API interface changed again. What's the best way to debug it now?

**Comment by tigerbrain** [comment]
Same here.  Code stopped working this morning for me as well.  :(

**Comment by bhusang** [comment]
Found the problem -- login api has changed pretty significantly (GET changed to POST, token handling needed, APP_ID changed, etc). Don't have the time to fix it right now but will take a look later. Here's a reference project that already figured out the changes:  https://github.com/Einstein42/myq-garage

**Comment by tigerbrain** [comment]
Great find @bhusang.  I had a feeling that this was going to change somehow because the GET method poses a security issue since the password is being transmitted unencrypted.  This is a step towards the right direction for Chamberlain, but yes unfortunately for us, we will now have to modify or codes again.  But as long as we know what the new endpoints are.  I am confident that we will be able to figure it out.  Thanks for sharing your discovery.

**Comment by jbnunn** [comment]
Thanks all, updated based @arraylabs discoveries. The Chamberlain updates are a pain, but as @tigerbrain said it's a step in the right direction towards a real app.

**Comment by SConaway** [comment]
works now just keep symbols in user/pass

**Comment by nimustan** [comment]
Should I be changing my username and password for myq due to the mentioned security issue?

**Comment by tigerbrain** [comment]
Hi @nimustan, I don't think you really have to, but if you don't feel comfortable about your password being exposed before.  Of course, you are free to do that.  I was personally ok with it cause I figured that nobody knows where I live anyway so they probably won't care about trying to hack into my garage.

**Comment by tigerbrain** [comment]
Thanks @jbnunn for putting in the fixes so quickly and thank you again @arraylabs for saving us from having to miss out on this wonderful luxury.

**Comment by CelticWebSolutions** [comment]
I'm now getting a different error, I'm sure the username and password are correct and I use date encoder from the instructions to alter is.  The log now says 



17:25:06
START RequestId: b118cd08-f3a3-11e6-bf9a-b1a8e2b0abd0 Version: $LATEST

17:25:07
'SecurityToken': KeyError Traceback (most recent call last): File "/var/task/main.py", line 31, in lambda_handler login() File "/var/task/main.py", line 99, in login myq_security_token = auth['SecurityToken'] KeyError: 'SecurityToken'

17:25:07
END RequestId: b118cd08-f3a3-11e6-bf9a-b1a8e2b0abd0

17:25:07
REPORT RequestId: b118cd08-f3a3-11e6-bf9a-b1a8e2b0abd0	Duration: 1111.90 ms	Billed Duration: 1200 ms Memory Size: 128 MB	Max Memory Used: 24 MB

17:25:07
START RequestId: b1ea266f-f3a3-11e6-b172-1dafaa018718 Version: $LATEST

17:25:08
'SecurityToken': KeyError Traceback (most recent call last): File "/var/task/main.py", line 31, in lambda_handler login() File "/var/task/main.py", line 99, in login myq_security_token = auth['SecurityToken'] KeyError: 'SecurityToken'

17:25:08
END RequestId: b1ea266f-f3a3-11e6-b172-1dafaa018718

17:25:08
REPORT RequestId: b1ea266f-f3a3-11e6-b172-1dafaa018718	Duration: 884.67 ms	Billed Duration: 900 ms Memory Size: 128 MB	Max Memory Used: 24 MB

**Comment by ishan11** [comment]
I update the code changes that were published yesterday, however I am getting an error that is referencing the ASK skill id. I have double checked that the ID is correct. I am not sure what I am doing wrong. Any help would be appreciated.


START RequestId: 143c252c-f3a8-11e6-9996-e913311612ab Version: $LATEST
'session': KeyError
Traceback (most recent call last):
  File "/var/task/main.py", line 24, in lambda_handler
    if event['session']['application']['applicationId'] != "amzn1.ask.skill.229939cb-c632-4b39-b57a-fcd3beca4c79":
KeyError: 'session'

**Comment by tigerbrain** [comment]
@CelticWebSolutions, FYI, I also experienced your error last night as I was editing my code to implement the changes @jbnunn implemented.  Before I experienced the problem, I was able to actually call the login() procedure multiple times with success.  So when I started getting a failed message, I decided to just call it a night thinking that maybe Chamberlain was updating their system which is causing my calls to fail already.  It was a good decision because this morning, I tried the exact same code again with success.  So I don't know if this is the exact situation for you, but just wanted you to know that it may be a problem with Chamberlain's new API and not your code?  Just a thought.

**Comment by CelticWebSolutions** [comment]
Thanks @tigerbrain, maybe I'll just leave it till tomorrow morning and see what happens then 👍

**Comment by davedyk** [comment]
Hey; Thanks so much for updating this so quickly.

I am seconding what @SConaway alludes to.  I had previously encoded my email and password.  With the new API, those encoded strings, the login was failing.  I just passed in the actual email and password directly, and it works now.

**Comment by SConaway** [comment]
@davedyk The PR from @tigerbrain works wonderfully.

**Comment by tigerbrain** [comment]
Hi All,

Just to be clear, now that Chamberlain's new API has been updated to use a POST instead of a GET.  The username and password must no longer be encoded which is consistent with @SConaway and @davedyk's discovery.  I will create another pull request to make sure that the step by step instructions are updated accordingly.

@CelticWebSolutions, was your issue resolved after waiting for one day without doing anything?

tigerbrain

**Comment by CelticWebSolutions** [comment]
Hi Tigerbrain, 

No it wasn't but I just read that we didn't need the @ encoding and to simply use the @ in the email and it worked.  Just changed mine to have just a  straight forward @ and mine now works again too :)
