### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by Firesprinklerman** [jbnunn/Alexa-MyQGarage#25]
received following error

START RequestId: 3dc6c294-fc78-11e6-a745-efa006dffcd1 Version: $LATEST
Syntax error in module 'main': expected an indented block (main.py, line 154)

END RequestId: 3dc6c294-fc78-11e6-a745-efa006dffcd1
REPORT RequestId: 3dc6c294-fc78-11e6-a745-efa006dffcd1

**Comment by tigerbrain** [comment]
Hi @firesprinklerman, is this still an issue for you?  If yes, I suggest that you redownload and re-edit the main.py file again ensuring this time that you don't mistakenly add or remove any leading spaces or tabs at the beginning of each line of code because Python is very sensitive to this.

Another thing you can do is to start from scratch and use the following version of the code instead: https://github.com/tigerbrain/Alexa-MyQ-WithMultiDoorSupport as it does not require you to edit the main.py file and uses the Lambda environment variables feature instead.  But I caution you to start from the beginning and follow the instructions carefully as there are some subtleties between the two installation methods that you could easily overlook if you are not careful.

**Comment by Firesprinklerman** [comment]
Thank you. I have a question, do I leave just the "....." for my chamberlain username and pass word or do I include "<.....>"? Sorry for the stupid question. This is wonderful what you are providing.

Mike

________________________________

**Comment by jbnunn** [comment]
Hi @Firesprinklerman ... you don't need the < or >

**Comment by jbnunn** [comment]
@Firesprinklerman as for the error `Syntax error in module 'main': expected an indented block (main.py, line 154)`, this is likely a spacing issue. Python is picky about indents. Can you paste lines 150-154?

**Comment by Firesprinklerman** [comment]
Starting over with new file….will let you know in a few…



*From:* J. Nunn [mailto:notifications@github.com]
*Sent:* Monday, February 27, 2017 5:53 PM
*To:* jbnunn/Alexa-MyQGarage <Alexa-MyQGarage@noreply.github.com>
*Cc:* Firesprinklerman <Michaeldupree1019@gmail.com>; Mention <
mention@noreply.github.com>
*Subject:* Re: [jbnunn/Alexa-MyQGarage] Error Message (#25)



@Firesprinklerman <https://github.com/Firesprinklerman> as for the error Syntax
error in module 'main': expected an indented block (main.py, line 154),
this is likely a spacing issue. Python is picky about indents. Can you
paste lines 150-154?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jbnunn/Alexa-MyQGarage/issues/25#issuecomment-282883525>,
or mute the thread

**Comment by Firesprinklerman** [comment]
Works perfect. Thanks for taking the time to create this. Awesome. Thanks
again.



*From:* J. Nunn [mailto:notifications@github.com]
*Sent:* Monday, February 27, 2017 5:53 PM
*To:* jbnunn/Alexa-MyQGarage <Alexa-MyQGarage@noreply.github.com>
*Cc:* Firesprinklerman <Michaeldupree1019@gmail.com>; Mention <
mention@noreply.github.com>
*Subject:* Re: [jbnunn/Alexa-MyQGarage] Error Message (#25)



@Firesprinklerman <https://github.com/Firesprinklerman> as for the error Syntax
error in module 'main': expected an indented block (main.py, line 154),
this is likely a spacing issue. Python is picky about indents. Can you
paste lines 150-154?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jbnunn/Alexa-MyQGarage/issues/25#issuecomment-282883525>,
or mute the thread
